"""Which progression flag gates which block, across every script.

The interpreter has three flag instructions (see docs/engine_notes.md):

    0c <flag> <addr>   jump to <addr> if SET   - the code after it runs when CLEAR
    0d <flag> <addr>   jump to <addr> if CLEAR - the code after it runs when SET
    1d <flag>          set the flag

(The direction was confirmed by running it: the manor Chancellor's introduction behind
`0c 73 00 <addr>` in 03YSK01B plays with flag 0x73 clear. An earlier version of this
docstring had 0c/0d the wrong way round; the table below only records which files set
and test each flag, so it was never affected.)

and the flags themselves are a bit array at 16d8:08d2. Decoding every script therefore
says, statically, what each flag controls: which blocks test it, and which set it. That
is the map behind "why can't the autoplayer get past this point" - and the list of
flags to write if you want to jump the story forward.

    python tools/flag_map.py                 # docs/flag_map.md
    python tools/flag_map.py --flag 0x1e2    # just this one
"""
import argparse
import collections
import glob
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # the project root; this file is in tools/
sys.path.insert(0, HERE)
import script_decode as sd                     # noqa: E402

TEST_CLEAR, TEST_SET, SET_FLAG = 0x0c, 0x0d, 0x1d


def scan():
    """flag -> {'tested': [(file, block)], 'set': [(file, block)]}"""
    out = collections.defaultdict(lambda: {'tested': [], 'set': []})
    files = 0
    for path in sorted(glob.glob(os.path.join(HERE, 'original', 'decompressed', '*.SCN'))):
        fn = os.path.basename(path)
        try:
            r = sd.analyse(fn)
        except Exception:
            continue
        if not r:
            continue
        files += 1
        for at, op, values in r['insns']:
            if op in (TEST_CLEAR, TEST_SET, SET_FLAG) and values:
                flag = values[0][2]
                where = (fn, at)
                out[flag]['set' if op == SET_FLAG else 'tested'].append(where)
    return out, files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--flag', help='report only this flag (hex)')
    ap.add_argument('--out', default=os.path.join('docs', 'flag_map.md'))
    args = ap.parse_args()
    flags, files = scan()
    if args.flag:
        f = int(args.flag, 16)
        info = flags.get(f)
        print('flag %#06x: set by %s; tested by %s'
              % (f, info['set'] if info else '-', (info['tested'][:8] if info else '-')))
        return
    os.makedirs(os.path.dirname(args.out) or '.', exist_ok=True)
    with open(args.out, 'w', encoding='utf-8') as fh:
        def out(*t, **kw):
            print(*t, file=fh, **kw)

        out('# What each progression flag gates', end='\n\n')
        out('Generated by `flag_map.py` from %d decoded scripts. Flags live in the bit'
            % files)
        out('array at 16d8:08d2 (flag N = bit N&7 of byte 0x8d2 + N/8); `tools/flags.py`')
        out('reads and diffs them in a save state.', end='\n\n')
        out('A flag with setters and testers in different files is a story gate: the')
        out('event that sets it is in one place, the door that checks it in another.',
            end='\n\n')
        out('| flag | set by | tested by |')
        out('|---|---|---|')
        for f in sorted(flags):
            info = flags[f]
            sets = ', '.join('%s %#06x' % w for w in info['set'][:3]) or '-'
            tests = ', '.join('%s %#06x' % w for w in info['tested'][:3]) or '-'
            extra = ''
            if len(info['tested']) > 3:
                extra = ' +%d' % (len(info['tested']) - 3)
            out('| %#06x | %s | %s%s |' % (f, sets, tests, extra))
    never_set = [f for f, i in flags.items() if i['tested'] and not i['set']]
    print('%d flags across %d scripts -> %s' % (len(flags), files, args.out))
    print('%d flags are tested but never set by any script (set elsewhere, or dead): %s'
          % (len(never_set), ' '.join('%#x' % f for f in sorted(never_set)[:12])))


if __name__ == '__main__':
    main()
